language: node_js
node_js:
  - "lts/*"
cache: yarn
script:
  - npm run build
  - npm test
deploy:
  provider: npm
  email: zebrap25@gmail.com
  api_key:
    secure: jwTzqrsmzOr6efnW++cdvn893RpCp1TfBsQWlZt3CHmznL4mXAlMXYerppEIK9MrSl0LeqdpQmhfmdkrHE1bEvetng8Ig6Aeqg6DtjjNMF0t03CLePpBCtXS5RMweZCwe5GM/63zhO/8jIIFi+4p5Yls+tfbzKzsn3Y1auDh2ryaFRY8KZ4PTrXkZuECL+wN3lPlN2rp37nhVMJRCmS5VN9+hKjIxQa4AT+Snpz8eu+WpD2ZZWKxfO5rXy4fr8Tm7Pd+PRcmzIRXh4ckX/RP5wtJOyD2H4qQ7SeTxkmK4vdVEie9S3T7hq8WVHCpDd/U5UzgLKscPrgHRuT3oCSAkQgwRf+VUd9WaRL17o97rVtze9P+r+q78Eu5V6ZfIlHjyRRFQHYhbbEWKM1jf3OdDSy2abiAYyRrD77CgmGBum1YURA4CIHqyrm9dhQVW8TILaGvtHbo8ffcZ1aatKaP2aqjIQZngPJ0uWkZzvXSo5/YalWgYedAUBfByjBQClbZ7vIzDj4fpU5HHlj2t/Ak3x3iEBpRah4riglTLB1lHRnMjOnkB4hqa7qFVA5sQDf7PP/cASejIPEfszoEbzHmZYzBcW3bfbiPFEZTTjwvPDE0jyeM7z02+DA8haDyaoLkteFWWqyVT3IQXSU8jGSwgexAQyZ5aNFWeoZSwfMNx7I=
  on:
    branch: master
