language: node_js
node_js:
  - "lts/*"
cache: yarn
script:
  - npm run build
  - npm test
deploy:
  provider: npm
  email: zebrap25@gmail.com
  api_key:
    secure: Wbl7Osg3xAJEAOLDFHVZTENl8Rh+ZykPB1OpULgq1J//JU9Y2E9dzFu9ytWODISVUip7qauFqbzFBWSHpSkjxvneUl52yTvESP1//k8njzeExoaP4LyqEszdi58dQfKoxE/wgv76DImuVYnqPrP31h63VjBW2MJFSUHrIc2AWs009Ocv0QGBdjFWxguaeympxgA0lYxcFIqVHq/TIu6g1YksAj+i2n35o5XZWG+gi3ac6d/xmFsZTkSsA8jdQ6WcQ37qq28Kg1YNEKp2f8ewMcM2+eca0Mj1WE2fUVYlS+QhsTnN5B56t4utVj7KKd/KfKvYAMGShXQlZUe9Lr4DgtP6KutM1P9Pu8LVLQdgg1clSx9JvO9R84lAi18Tzsc2h8tOo1wedp08JrrJQCSCbxOP3pk9Pdkt0ZiF48x1xpMlk/ACwHQaRlN01o48wNpR84zhKPHR7BwPUFvLiSRhaCleVfgla4xhMhIepgXmA134DdAb6OFNp1olZJMkrN2FytafBYL+KGr4D9rb9H235sEHS4tnBeWL4GMDsub+RfKozg7O2hJs+z3jZfnj/vwmP1IKqfg9mRa5vyvcS0SoUzl2fOx6bYt4ow5M9ayJoe5c2mqjK6npy8CsA/ASvExxtf4UmCwHfKXOr2yQ3qqx45oLyjCzCSsNz64NHfptkOM=
  on:
    branch: master
